name: Social Readme

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  update-social:
    runs-on: ubuntu-latest
    steps:
      - uses: tiandankanfeng/social-readme@master
        with:
          blog_rss_link: https://liangye-xo.xyz
          douban_name: your douban username
